var source = {

	// Random words to grab from an array
	basic: [
		["the","be","to","of","and","a","in","that","have","I","it","for","not","on","with","as","you","do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my","one","all","would","there","their","what","so","up","out","if","about","who","get","which","go","me","when","make","can","like","time","no","just","him","know","take","people","into","year","your","good","some","could","them","see","other","than","then","now","look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way","even","new","want","any","these","give","day","most","us","quick","stop"],
		["the","be","of","and","a","to","in","he","have","it","that","for","they","I","with","as","not","on","she","at","by","this","we","you","do","but","from","or","which","one","would","all","will","there","say","who","make","when","can","more","if","no","man","out","other","so","what","time","up","go","about","than","into","could","state","only","new","year","some","take","come","these","know","see","use","get","like","then","first","any","work","now","may","such","give","over","think","most","even","find","day","also","after","way","many","must","look","before","great","back","through","long","where","much","should","well","people","down","own","just","because","good","each","those","feel","seem","how","high","too","place","little","world","very","still","nation","hand","old","life","tell","write","become","here","show","house","both","between","need","mean","call","develop","under","last","right","move","thing","general","school","never","same","another","begin","while","number","part","turn","real","leave","might","want","point","form","off","child","few","small","since","against","ask","late","home","interest","large","person","end","open","public","follow","during","present","again","hold","govern","around","possible","head","consider","word","program","problem","however","lead","system","set","order","eye","plan","run","keep","face","fact","group","play","stand","increase","early","course","change","help","line","without","sentence","story","feet","carry","something","mountain","tree","night","quickly","young","water","stop","father","mother","forever","paper","answer","plant","children","thought","dollar","above","add","air","almost","along","always","an","animal","are","away","been","began","being","below","big","book","boy","came","car","city","close","country","cut","did","different","does","don't","earth","eat","enough","every","example","family","far","food","found","four","girl","got","grow","had","hard","has","hear","her","him","his","idea","important","is","its","it's","kind","land","later","learn","left","let","letter","light","list","live","made","me","men","mile","miss","my","name","near","next","often","oil","once","our","page","picture","put","question","quick","quite","read","really","river","said","saw","sea","second","side","sometimes","song","soon","sound","spell","start","study","talk","their","them","three","together","took","try","two","until","us","walk","was","watch","went","were","white","why","your"],
		["machined", "officiator", "secondary", "tertiary", "quaternary", "threadbare", "investment", "procedure", "kingdom", "important", "validation", "divestiture", "circumnavigate", "taciturn", "bildungsroman", "sanguine", "capacious", "sycophant", "duplicitous", "milieu", "diaspora", "propitious", "cognoscenti", "anathema", "portentous", "ostentatious", "soporific", "commensurate", "tautology", "histrionic", "bifurcation", "equanimity", "prognosticate", "prostrate", "beleaguer", "unscrupulous", "lachrymose", "prescient", "partnership", "jurisdiction", "shareholders", "bioluminescence", "classification", "therapeutic", "homeopathic", "licensing", "macronutrients", "unaccountable", "cappuccino", "electricity", "hieroglyph", "kaleidoscope", "restaurant", "thermometer", "typewriter", "disability", "questionable", "painstaking", "nebulous", "nauseating", "earsplitting", "knowledgeable", "illustrious", "picayune", "bewildered", "frightening", "sweltering", "incompetent", "squeamish", "synonymous", "comprehensive", "lamentable", "vegetation", "stimulating", "sophisticated", "scandalous", "mountainous", "quarrelsome", "stereotyped", "disillusioned", "acoustical", "cooperative", "laborious", "evanescent", "auspicious", "rambunctious", "omniscient", "incandescent", "whimsical", "marvelous", "permissible", "caucus", "overwrought", "brainstorm", "chlamydia", "monotonous", "polyunsaturated", "imbalance", "database", "compounded", "pronunciation", "malfunction", "progesterone", "particularly", "intravascular", "electrolyte", "frequency", "amplitude", "oscillation", "reverberation", "algorithm", "migratorial", "infrastructure", "hummingbird", "troglodyte", "milkweed", "necropsy", "unsatisfactory", "euthanized", "anasthesia", "veterinarians", "mongolian", "christianity", "landlocked", "shakedown", "vandalization", "tergiversation"]
	],

	// Continous sentences
	sentence: [
		"Suddenly Frodo noticed that a strange-looking weather-beaten man, sitting in the shadows near the wall, was also listening intently to the hobbit-talk. He had a tall tankard in front of him, and was smoking a long-stemmed pipe curiously carved. His legs were stretched out before him, showing high boots of supple leather that fitted him well, but had seen much wear and were now caked with mud. A travel-stained cloak of heavy dark-green cloth was drawn close about him, and in spite of the heat of the room he wore a hood that overshadowed his face; but the gleam of his eyes could be seen as he watched the hobbits.",
		"October arrived, spreading a damp chill over the grounds and into the castle. Madam Pomfrey, the nurse, was kept busy by a sudden spate of colds among the staff and students. Her Pepperup potion worked instantly, though it left the drinker smoking at the ears for several hours afterward. Ginny Weasley, who had been looking pale, was bullied into taking some by Percy. The steam pouring from under her vivid hair gave the impression that her whole head was on fire. Raindrops the size of bullets thundered on the castle windows for days on end; the lake rose, the flower beds turned into muddy streams, and Hagrid's pumpkins swelled to the size of garden sheds. Oliver Wood's enthusiasm for regular training sessions, however, was not dampened, which was why Harry was to be found, late one stormy Saturday afternoon a few days before Halloween, returning to Gryffindor Tower, drenched to the skin and splattered with mud. Even aside from the rain and wind it hadn't been a happy practice session. Fred and George, who had been spying on the Slytherin team, had seen for themselves the speed of those new Nimbus Two Thousand and Ones. They reported that the Slytherin team was no more than seven greenish blurs, shooting through the air like missiles.",
		"All was confusion in the Oblonskys' house. The wife had found out that the husband was having an affair with their former French governess, and had announced to the husband that she could not live in the same house with him. This situation had continued for three days now, and was painfully felt by the couple themselves, as well as by all the members of the family and household. They felt that there was no sense in their living together and that people who meet accidentally at any inn have more connection with each other than they, the members of the family and household of the Oblonskys. The wife would not leave her rooms, the husband was away for the third day. The children were running all over the house as if lost; the English governess quarrelled with the housekeeper and wrote a note to a friend, asking her to find her a new place; the cook had already left the premises the day before, at dinner-time; the kitchen-maid and coachman had given notice.",
		"The Wheel of Time turns, and Ages come and pass, leaving memories that become legend. Legend fades to myth, and even myth is long forgotten when the Age that gave it birth comes again. In one Age, called the Third Age by some, an Age yet to come, an Age long past, a wind rose in the Mountains of Mist. The wind was not the beginning. There are neither beginnings nor endings to the turning of the Wheel of Time. But it was a beginning. Eastward the wind blew, descending from lofty mountains and coursing over desolate hills. It passed into the place known as the Westwood, an area that had once flourished with pine and leatherleaf. Here, the wind found little more than tangled underbrush, thick save around an occasional towering oak. Those looked stricken by disease, bark peeling free, branches drooping. Elsewhere needles had fallen from pines, draping the ground in a brown blanket. None of the skeletal branches of the Westwood put forth buds.",
		"No, comrades, a thousand times no! The soil of England is fertile, its climate is good, it is capable of affording food in abundance to an enormously greater number of animals than now inhabit it. This single farm of ours would support a dozen horses, twenty cows, hundreds of sheep -- and all of them living in a comfort and a dignity that are now almost beyond our imagining. Why then do we continue in this miserable condition? Because nearly the whole of the produce of our labour is stolen from us by human beings. There, comrades, is the answer to all our problems. It is summed up in a single word -- Man. Man is the only real enemy we have. Remove Man from the scene, and the root cause of hunger and overwork is abolished for ever. Man is the only creature that consumes without producing. He does not give milk, he does not lay eggs, he is too weak to pull the plough, he cannot run fast enough to catch rabbits. Yet he is lord of all the animals. He sets them to work, he gives back to them the bare minimum that will prevent them from starving, and the rest he keeps for himself. Our labour tills the soil, our dung fertilises it, and yet there is not one of us that owns more than his bare skin.",
		"The only person for whom the house was in any way special was Arthur Dent, and that was only because it happened to be the one he lived in. He had lived in it for about three years, ever since he had moved out of London because it made him nervous and irritable. He was about thirty as well, tall, dark-haired and never quite at ease with himself. The thing that used to worry him most was the fact that people always used to ask him what he was looking so worried about. He worked in local radio which he always used to tell his friends was a lot more interesting than they probably thought. It was, too-most of his friends worked in advertising. On Wednesday night it had rained very heavily, the lane was wet and muddy, but the Thursday morning sun was bright and clear as it shone on Arthur Dent’s house for what was to be the last time.",
		"It was night again. The Waystone Inn lay in silence, and it was a silence of three parts. The most obvious part was a hollow, echoing quiet, made by things that were lacking. If there had been a wind it would have sighed through the trees, set the inn's sign creaking on its hooks, and brushed the silence down the road like trailing autumn leaves. If there had been a crowd, even a handful of men inside the inn, they would have filled the silence with conversation and laughter, the clatter and clamor one expects from a drinking house during the dark hours of night. If there had been music... but no, of course there was no music. In fact there were none of these things, and so the silence remained.",
		"Two households, both alike in dignity, In fair Verona, where we lay our scene, From ancient grudge break to new mutiny, Where civil blood makes civil hands unclean. From forth the fatal loins of these two foe A pair of star-cross'd lovers take their life; Whose misadventured piteous overthrows Do with their death bury their parents' strife. The fearful passage of their death-mark'd love, And the continuance of their parents' rage, Which, but their children's end, nought could remove, Is now the two hours' traffic of our stage; The which if you with patient ears attend, What here shall miss, our toil shall strive to mend.",
		"The sun was shining brightly on the morning of the big day, but the ground was still white with snow and the air was very cold. Outside the gates of Wonka's factory, enormous crowds of people had gathered to watch the five lucky ticket holders going in. The excitement was tremendous. It was just before ten o'clock. The crowds were pushing and shouting, and policemen with arms linked were trying to hold them back from the gates. Right beside the gates, in a small group that was carefully shielded from the crowds by the police, stood the five famous children, together with the grown-ups who had come with them. The tall bony figure of Grandpa Joe could be seen standing quietly among them, and beside him, holding tightly on to his hand, was little Charlie Bucket himself. All the children, except Charlie, had both their mothers and fathers with them, and it was a good thing that they had, otherwise the whole party might have got out of hand. They were so eager to get going that their parents were having to hold them back by force to prevent them from climbing over the gates.",
		"As soon as the day began to break I put on my shoes and climbed a hill - the ruggedest scramble I ever undertook - falling, the whole way, between big blocks of granite, or leaping from one to another. When I got to the top the dawn was come. There was no sign of the brig, which must have lifted from the reef and sunk. The boat, too, was nowhere to be seen. There was never a sail upon the ocean; and in what I could see of the land was neither house nor man. I was afraid to think what had befallen my shipmates, and afraid to look longer at so empty a scene. What with my wet clothes and weariness, and my belly that now began to ache with hunger, I had enough to trouble me without that. So I set off eastward along the south coast, hoping to find a house where I might warm myself, and perhaps get news of those I had lost. And at the worst, I considered the sun would soon rise and dry my clothes.",
		"Two days after this, when Mary opened her eyes she sat upright in bed immediately, and called to Martha. \"Look at the moor! Look at the moor!\" The rainstorm had ended and the gray mist and clouds had been swept away in the night by the wind. The wind itself had ceased and a brilliant, deep blue sky arched high over the moorland. Never, never had Mary dreamed of a sky so blue. In India skies were hot and blazing; this was of a deep cool blue which almost seemed to sparkle like the waters of some lovely bottomless lake, and here and there, high, high in the arched blueness floated small clouds of snow-white fleece. The far-reaching world of the moor itself looked softly blue instead of gloomy purple-black or awful dreary gray."
	],

	// Store user-selected source content, from file
	file: undefined		

}

module.exports = source
